apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik-v3
spec:
  itemPath: "vaults/a4nh24gpadwwnvcqnww3txokwy/items/alaa2qrq5geu637sjc3trpdeqm"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
  namespace: traefik-v3
spec:
  acme:
    email: stevenbuglione1@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cloudflare-account-key
    solvers:
      - dns01:
          cloudflare:
            email: stevenbuglione1@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: credential

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-klustered-us
  namespace: traefik-v3
spec:
  secretName: wildcard-klustered-us-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - klustered.us
    - '*.klustered.us'
