apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default

  source:
    repoURL: https://github.com/StevenBuglione/k3s-argocd-boot
    path: registry/projects/development/cluster/apps/1password
    targetRevision: HEAD
    directory:
      recurse: true

  destination:
    name: in-cluster
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

