---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-example-com
  namespace: default
spec:
  secretName: local-klustered-us-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.klustered.us"
  dnsNames:
    - "local.klustered.us"
    - "*.local.klustered.us"