---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgByaozq3E+EwVt93JVqHZ4jiWgP3KSLxb0bMAsonqYzMFOfzTE9sA1WPyO2MCz5eXhb3oH0xmyslg1lGwMTDLuVZW3VtHsesi2J+7sPCzNx/6vdGLIeDy4vlrkYMSJc6uB8bw9i2Pv7Jf1xWEA5SYyrWnesmg3zld70KyOVnoi94o9PGM2wWq9W9cgLfns6oU9Tg3Wk5kkm7wyrPdhH/GKfwyEugknC5GU3Xza0/CqTdUg/o5UhJK5d5sYpxnZ3cY6BemrK57bBFAwqdGsVkQm9s7hXG7UMIXRs7rIPDIDl0UWCHkG/TmTIaR+RXTlP7XdqWahVu3bZQ2qB80E89XSh7dhNum6aSbu5zSpz+md4RC/Ik3Uz/mLaCj/pS6LuLq+yF/tNRWqRCRzz3Cf9evtLSOGCUlOHIo0UM8/SSk0w9HQtA+6vuPnPxxmApWXodTZxNFkJjPHzmdxhILwnAuVjDMWfVV03QC+C9TvpnyJ59HTx90OVLy/HCHqJeav+SP5i01rU+XI3siJgX76WYdNEhu9EBHBBfFvcv11lao6LkJPWfiQeb7f8qr9C4+uv3b55aJzx1C+paPTPgA3xn9ZcMeKXLG2Ps905nNrnsLjdsF77ww+6tJDZtAhCOxtps25Lx03pxwBgx6wE+4SDpai8JzzL8daL/8OJ0FHnlUw5ZSyH6vfPUbWBx8SfuKHfWtT59/Nk/q4q5Q6m13ah4U7hKjBScnlmyXZKuo4yiyRtVllgHJoXeh4r
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: email-secret
  namespace: cert-manager
spec:
  encryptedData:
    email: AgCRIZlTTWYwpXcWPrpDYDpneGDt/8Bqo2NtJEt0bD3gqoQlsVmOzw1GpHk4/KEvK97CzI+7ilD0Fxyrw74xhCWp5N6xSpT2vikpjjLGd8UaJAkutlSKs84mVMwnXSB0vBlOnOteofIbnrB9xVZv6h95Rd+Qh/47rSB+W1U9h+ayRleJ8T+I/tD3IDdsEHoGhjn9PvSIq9LZvPSn5GfSR/mDzKd511aU8BrkOQIkEpkLIyr7p5FZdBGFH/EYatvUtos4MeDVX2juH8Bv6/o93W74Gj226IgWPd8mAAEPyp9VCyNTmjPZJ+LvPIZWMUkmL04ak5BSYS2TpOkUNfpx9bKvhzHLsTZ8OrOlDeZ8nPRoCYaUoZXA1DlwYyjVhUVNouNWm81y/oHrkzmda5HqCYubHF5kBWfmLjuCNVPSAQI10rPmb8bjoL1Igv3xyGnZJvzfXRYVoB7m417XAZfCjitZ8LNzALjz1thL86i3XcNyAjsWoApLz1uNo8Vw6nJX1TyTNdBXN7dabgrsBAyPI0eEpvrDNIZv2N4Kr5IBW3VVKGzkMTvBwGmoogJmz73cLVMdroKYSEZhh3UJ2BYUHM37cJuJ7tJBWi70hCH470hiuMQX+25V2wNa3UP72pxlcRl5oW4GuyuGqcGSqpvimU71EeQIwuHEInumDaGi1ahVw3Fe6WMmFzsAT3w50PrbcvOpZVuxO2r3TnimlzfKWRY26g4ZYX3hD7Ou
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: email-secret
      namespace: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email:
      valueFrom:
        secretKeyRef:
          name: email-secret
          key: email
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email:
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "klustered.us"
