apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  destination:
    namespace: default
    name: in-cluster
  project: development
  source:
    path: registry/projects/development/cluster/apps
    repoURL: https://github.com/StevenBuglione/k3s-argocd-boot
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true