apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-creds
  namespace: development
spec:
  encryptedData:
    origin-ca-api-key: AgAwg+Q3idn85zOzGFZuiE4cfNZXrFi2iIhNd32g/HJ5kqJUrXFq0mc7TCG/c0DBbTGbL6+QlQOsmB7qRe5c+thHn9qB/xMPGUp+PJmV+LFrTckQIapkW/3CCMjW7U4qq25hgGtoYxMb5IzVuKyjVLE6EGJZuZDzZRQa19V/znNUKKnwwl4V+uedChzSOb/aCKOfSN1uBdi4i2lsz1MSDUnGxuSLzCfpRzLUW4rkJziKr3016qxzBGqN8sWnV8hJt1khZGEsTjr9fiOOJHlwCyvPsXm2bfa87a6Gl0EzQbozfKLU9icufPy1EtM/m1GDRx00rak3Dml0JX7KgFDlQ7OlxO1a+2GyZQ9WY95+d2UxV0BOU5iMmoykBDY8fC2yb39jXqJbGKGL0GnlYUE1bDhMWZMn2R8H3n31DBlJ11TqiYSkvLBwA1pVlmXV2QZr2qQQcZGjxm9CfJt4koYTCzmFU0FhvwHx6ZeppwdAkPqw3m7RivIIvY5pZbOEkdlc2IGqU2i5nCrRCht0rep83VwBlEBieULknWck8E1kfL7D7mCppHUuf1zSH9Fm/s9AAIJCsNDb9Nsq6QDyo6KWg8V/z0dHnG58F6eUTXq3gvxZ+Oquj+hKckcInpbnXCVcZTXygsQQ5DRNq3zWnHnPJC1T+GgUkpv63G8UQuUTiT4lZBgXo0bAuzVwxGuDAvZFvqjz7mID4PWcBXSVrIS7IITT9h+Xw7keKEw5VF5DHl8cyzedjjCahufPhVQkEavEV9bKEKSC7Pl3ppmhmzFYaKmxQ9QrztWzXml+Wb5w7v2N240brNjdmlruPdwJ7XJzl30Pb/hHuJyIETpfNSCVDPbVad7OoGwwpWxV29U1GOMC3ZiwxEiUYSdHptu/Ttcw/ASyjKaXKUrGuh3xGYIOxWDYR/2Bx9hvdwbS+JfBHGZTtw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-creds
      namespace: development
---
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
 name: cloudflare-origin-issuer
 namespace: development
spec:
 requestType: OriginECC
 auth:
   serviceKeyRef:
     key: origin-ca-api-key
     name: cloudflare-creds