apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-creds
  namespace: development
spec:
  encryptedData:
    cloudflare: AgAo/4ZrJ47qFLH4/v80HLoR0YMZaCVRfhJg7W4uGUj1b1Qsis6xclsTG/ZhOVySZzb54BxyWAnP+dEOjqcu/+VpzF1+/BlnxH4J0cEONlqI2Yd7IAlzMYjVMZGtCv6g/PeU6TAfUs5IaiYjUGMoUHq4a/gQakyivL8YiuNmT2oS+TS4t8cBwd6I5myHniNvczei9p6TZz69XsSWVjRWcpPq09MT3UN0bMN3nE9Xcr6nrXzcsHqCAY/QM61HgB3oBsKNqssdwXVH+GyDF+fJGfyCde0DhR/tJKJlWy/rMhvxmSq3eG9zt11a1ej6l0i1uEiuHbyFgkDGjVCbhOnhVNS4QRfc2WEzIXAlt2opPqqDuk8Zet8p4/G3rEHqIw4/3HHN16QRfy6QCzK74VmcgK86UXjbjeE/pwsTuGmvro80jcvsqz6czC4uRvVr2hSvJYof3/Iq0DNJMxIFqNju32b2+er+crEo/0+eB1AjGrCnE+i6VLUkAP1cASawsf3Eic3mZUOw8mNMXQ9yhf3yGdGetNOeENw+1tOyfr9BeQcf5cBQnjRnSwhTQqbtpzC7UtyclTka7S7eFciKA7IiuPI8VY+c9DmKew+H2ncEuT8PCTMECq7dBACMY32pWuHccJHKkJYljNtSIZpkly49U/1R0wJsYOwvLus6Zgb5XLeY1pE3kDB5kh7JvXSLuhobfI2/FqE7AMxkYOwsvh0TvYgMX00hoSn3F2UbxI9iaT55WD3AHM5fEF2QP6gilMXX3r3b3NPkWT+fFdJmK/EfGvBTXPrRM66Sjboj8V3TaDXYFv/WYUbmo4hsIkf1YtWFQGKw+vYWaDMWXYdSMoiVe7MdZ4x8X/OnL7aqmHImE0n+TugbpdVMoh29HvvG0cbXZR99CWLkGwjGkF9VtRbKr+TAsefksnYaDbVLIsU2NTp25Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-creds
      namespace: development
---
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
 name: cloudflare-origin-issuer
 namespace: development
spec:
 requestType: OriginECC
 auth:
   serviceKeyRef:
     key: origin-ca-api-key
     name: cloudflare-creds