apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vip-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: https://github.com/StevenBuglione/k3s-argocd-boot
    path: registry/projects/development/cluster/mgmt/vip-config
    targetRevision: develop
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    ignoreDifferences:
      - group: apps
        kind: DaemonSet
        jsonPointers:
          - /status
    syncOptions:
      - CreateNamespace=true