apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: development
  source:
    repoURL: https://github.com/StevenBuglione/k3s-argocd-boot
    path: registry/projects/development/cluster/mgmt/metallb-config
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true