apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '11'
spec:
  project: default
  source:
    repoURL: https://1password.github.io/connect-helm-charts/
    chart: connect
    targetRevision: 1.16.0
    helm:
      parameters:
        - name: operator.create
          value: "true"
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true