apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '12'
spec:
  project: development
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.11.0
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
        replicaCount: 1
        extraArgs:
          - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
          - --dns01-recursive-nameservers-only
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - 1.1.1.1
            - 9.9.9.9
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true