apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default

  # -------------------------------------------------
  # Helm chart source
  # -------------------------------------------------
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 35.2.0
    helm:
      ## Everything under this block ends up in values.yaml
      values: |
        ingressRoute:
          dashboard:
            enabled: true
            # Custom match rule with host domain
            matchRule: Host(`traefik.klustered.us`)
            entryPoints: ["websecure"]
            # Add custom middlewares : authentication and redirection
            middlewares:
              - name: traefik-dashboard-auth

  # -------------------------------------------------
  destination:
    name: in-cluster
    namespace: traefik-v3

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

