apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 35.2.0           # same version as before
    helm:
      #
      # The inline values block below becomes the chart’s values.yaml.
      #
      values: |
        # --- Traefik service exposed through MetalLB --------------------------
        service:
          type: LoadBalancer
          loadBalancerIP: 10.10.10.30             # <‑‑ pick an IP in your pool
          annotations:
            metallb.universe.tf/address-pool: lan-pool   # <‑‑ name of the pool
        #
        # (optional) expose the usual HTTP/S ports
        #
        ports:
          web:
            expose:
              default: true
            exposedPort: 80
          websecure:
            expose:
              default: true
            exposedPort: 443
  destination:
    name: in-cluster
    namespace: traefik-v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
