apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '13'
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: connect
    targetRevision: 35.2.0
  destination:
    name: in-cluster
    namespace: traefik-v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true