apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 35.2.0
    helm:
      values: |
        ingressRoute:
          dashboard:
            enabled: true

        ports:
          web:
            expose: true
            exposedPort: 80
            protocol: TCP

        service:
          enabled: true
          type: LoadBalancer

        # Middleware, router, and entrypoint for the dashboard
        additionalArguments:
          - "--entrypoints.web.address=:80"
          - "--api.dashboard=true"

        # Custom IngressRoute for dashboard
        dashboards:
          enabled: true

        ingressRoute:
          dashboard:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
            matchRule: Host(`traefik.klustered.us`)
            entryPoints:
              - web

  destination:
    name: in-cluster
    namespace: traefik-v3

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

