apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: development
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: 24.0.0
    chart: traefik
    helm:
      values: |
        additionalArguments:
          - "--providers.kubernetesingress.ingressendpoint.publishedservice=networking/traefik"
          - "--experimental.plugins.theme-park.modulename=github.com/packruler/traefik-themepark"
          - "--experimental.plugins.theme-park.version=v1.2.2"
          - "--serverstransport.insecureskipverify=true"
        service:
          spec:
            externalTrafficPolicy: Local
            loadBalancerIP: "192.168.1.31"
          annotations:
            metallb.universe.tf/allow-shared-ip: traefik
      
        experimental:
          plugins:
            enabled: true
        
        ports:
          websecure:
            tls:
              enabled: true
          traefik:
            expose: true
          mailsecure:
            port: 465
            expose: true
            exposedPort: 465
          web:
            redirectTo: websecure
          metrics:
            expose: true
      
        providers:
          kubernetesCRD:
            allowExternalNameServices: true
            allowEmptyServices: true
          kubernetesIngress:
            allowExternalNameServices: true
            allowEmptyServices: true
            publishedService:
              enabled: true
        logs:
          general:
            level: DEBUG
          access:
            enabled: true
        ingressRoute:
          dashboard:
            enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true