apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/ignore: |
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: certificaterequests.cert-manager.io
spec:
  project: default
  source:
    repoURL: https://github.com/StevenBuglione/k3s-argocd-boot
    path: registry/projects/development/cluster/mgmt/cert-manager-config/cert-manager-crds
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true