apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-native
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/metallb/metallb
    path: config/manifests/metallb-native.yaml
    targetRevision: v0.14.4
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true