apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-crds.yaml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metallb/metallb
    path: metallb/config/manifests/metallb-native.yaml
    targetRevision: v0.13.9
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true