apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-dashboard
  namespace: argocd
spec:
  routes:
    - match: Host(`argocd.klustered.us`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          scheme: https
  tls:
    passthrough: true
