apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: onepassword-connect
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`op.klustered.us`)
      services:
        - name: onepassword-connect
          port: 8080
