apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-k3s-argocd-boot-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: k3s-argocd-boot-project-dev
  source:
    path: registry/projects/development/cluster
    repoURL: https://github.com/StevenBuglione/k3s-argocd-boot
    targetRevision: develop