apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-acme-pvc
  namespace: traefik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  storageClassName: nfs
  volumeName: nfs-acme-pv
