apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: mongodb-0
      port: 2701
      targetPort: mongodb-0
    - protocol: TCP
      name: mongodb-1
      port: 2702
      targetPort: mongodb-1
    - protocol: TCP
      name: minio-api
      port: 9000
      targetPort: minio-api
    - protocol: TCP
      name: minio-console
      port: 9001
      targetPort: minio-console
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: mysql
    - protocol: TCP
      name: mysql-read
      port: 3307
      targetPort: mysql-read
  providers:
    kubernetesIngress:
      ingressEndpoint:
        ip: 80.70.60.50

  externalTrafficPolicy: Local  
  selector:
    app: traefik


---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: traefik
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: admin
  selector:
    app: traefik
