kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.9
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --entrypoints.mongodb-0.address=:2701/tcp
            - --entrypoints.mongodb-1.address=:2702/tcp
            - --entrypoints.minio-api.Address=:9000
            - --entrypoints.minio-console.Address=:9001
            - --entrypoints.mysql.address=:3306/tcp
            - --entrypoints.mysql-read.address=:3307/tcp
            - --providers.kubernetescrd
            - --certificatesresolvers.myresolver.acme.tlschallenge
            #- --certificatesresolvers.myresolver.acme.email=youremail@gmail.com
            - --certificatesresolvers.myresolver.acme.storage=/data/acmes.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            - --certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: mongodb-0
              containerPort: 2701
              protocol: TCP
            - name: mongodb-1
              containerPort: 2702
              protocol: TCP
            - name: minio-api
              containerPort: 9000
            - name: minio-console
              containerPort: 9001
            - name: mysql
              containerPort: 3306
              protocol: TCP
            - name: mysql-read
              containerPort: 3307
              protocol: TCP
            - name: admin
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-acme-pvc
